# Generated by Django 5.2.1 on 2025-06-12 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_marketuser_user_type_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, help_text='Квартира', max_length=15, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, help_text='Строение', max_length=15, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(help_text='Город', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, help_text='Дом', max_length=15, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Телефон', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(help_text='Улица', max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, help_text='Корпус', max_length=15, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь которому принадлежат контакты', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Номер телефона, максимум 20 символов', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Seller', 'Продавец'), ('Buyer', 'Покупатель'), ('Admin', 'Администратор')], default='Buyer', help_text='Тип пользователя. Seller - продавец, Buyer - покупатель, Admin - администратор. По умолчанию - покупатель', max_length=20, null=True),
        ),
    ]
