# Generated by Django 5.2.3 on 2025-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_contact_apartment_alter_contact_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
