# Generated by Django 5.2.3 on 2025-06-19 20:42

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_marketuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketuser',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
