# Generated by Django 5.2 on 2025-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Packed', 'Упакован'), ('Shipped', 'Отправлен'), ('Completed', 'Завершен'), ('Canceled', 'Отменен')], default='New', max_length=255),
        ),
    ]
