# Generated by Django 5.2.1 on 2025-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Указывает, доступен ли продукт для покупки'),
        ),
    ]
