# Generated by Django 5.2.1 on 2025-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(auto_created=True, default=True, help_text='Указывает, доступен ли продукт для покупки'),
        ),
    ]
