# Generated by Django 5.2.1 on 2025-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(auto_created=True, default=1, help_text='Количество продуктов в наличии у продавца'),
        ),
    ]
