# Generated by Django 5.2.1 on 2025-06-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_parameters_value_alter_product_quantity'),
        ('Users', '0003_alter_contact_apartment_alter_contact_building_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='categories', to='Products.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='Products.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение параметра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Указывает, доступен ли продукт для покупки', verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество продуктов в наличии у продавца', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Users.marketuser', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'seller')},
        ),
    ]
